### ISSUE TITLE
Velodyne alignment fixed!

### ISSUE THREAD

**Issue by lucarossini-iit** [ADVRHumanoids/perception_thesis#3]
Hi all,

I worked a bit also with @liesrock and @vigisushrutha23  on the misalignment problem of the velodyne between gazebo and rviz simulation. We could find a solution modifying a bit the centauro.urdf file. I kindly ask to Alessio to try this fix pulling the last version of CentauroConfig (master branch) and running perception.launch in PCL_Perception. In addition, be sure to set the right config file: `set_xbot_config CentauroConfig/centauro_basic.yaml`.

Waiting for a feedback.

**Comment by DavideAntonucci** [comment]
Hi @lucarossini-iit ,

I tested the updating done related on this issue and it works on my laptop.

Thanks a lot for the support.

**Comment by aled96** [comment]
Hi @lucarossini-iit  ,

I pulled the last version of CentauroConfig and everything works correctly.

Thank you.
